version: "3"
services:

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    links:
      - dispatcher:backend
    volumes:
      - ./config/nginx:/etc/nginx/conf.d

  # Dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:1.1.0
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config

  # Cache
  resource:
    image: semtech/mu-cache:0.5.0
    environment:
      - CACHE_BACKEND=http://backend

  backend:
    image: semtech/mu-cl-resources:1.15.0
    links:
      - database:database
    volumes:
      - ./config/resources:/config
    environment:
      - MU_APPLICATION_GRAPH=http://data.vlaanderen.be/id/dataset/cataloog

  ## Database
  database:
    image: tenforce/virtuoso:1.3.0-virtuoso7.2.2
    volumes:
      - ./data/db:/data
      - ./config/toLoad:/data/toLoad
    ports:
      - "8890:8890"
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://data.vlaanderen.be/id/dataset/cataloog"
